import Link from "next/link";

export const metadata = {
  title: "Terms of Service — StudyBuddy",
};

// Update these when the domain + entity are finalized.
const CONTACT_EMAIL = "support@yourdomain.com";
const EFFECTIVE = "July 12, 2026";

export default function TermsPage() {
  return (
    <main className="mx-auto min-h-screen max-w-3xl px-6 py-12 text-slate-800">
      <header className="mb-8 flex items-start justify-between gap-4">
        <div>
          <h1 className="text-3xl font-semibold tracking-tight text-slate-900">Terms of Service</h1>
          <p className="mt-2 text-sm text-slate-500">Effective {EFFECTIVE}</p>
        </div>
        <Link
          href="/"
          className="shrink-0 rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-sm font-medium text-slate-600 shadow-sm hover:bg-slate-50"
        >
          ← Back
        </Link>
      </header>

      <div className="space-y-6 text-sm leading-relaxed text-slate-600 [&_h2]:mt-8 [&_h2]:text-base [&_h2]:font-semibold [&_h2]:text-slate-900">
        <p>
          These Terms govern your use of StudyBuddy (the &ldquo;Service&rdquo;), which records
          lectures, transcribes them, and generates AI notes, deadlines, and study aids. By
          creating an account or using the Service, you agree to these Terms.
        </p>

        <h2>1. Your account</h2>
        <p>
          You must provide accurate information and keep your login secure. You are responsible for
          activity under your account. You must be old enough to form a binding contract in your
          jurisdiction and to consent to the processing described here.
        </p>

        <h2>2. Recording is your responsibility</h2>
        <p>
          <strong>You are solely responsible for ensuring you have the right to record.</strong>{" "}
          Laws on recording conversations vary by state and country (some require the consent of all
          parties), and your school or instructor may have its own policies. You agree to obtain any
          consent required and to comply with all applicable laws and institutional rules before
          recording any lecture or conversation. Do not use the Service to record where you are not
          permitted to.
        </p>

        <h2>3. Subscriptions &amp; billing</h2>
        <p>
          Paid plans are billed monthly in advance through Stripe. You can cancel anytime; access
          continues until the end of the current billing period. Plans include a monthly lecture
          allowance; fees are non-refundable except where required by law. We may change pricing on
          reasonable notice.
        </p>

        <h2>4. AI-generated content</h2>
        <p>
          Notes, summaries, deadlines, flashcards, and answers are generated by automated models and
          <strong> may be incomplete or inaccurate</strong>. Do not rely on them as a substitute for
          the lecture, official course materials, or professional advice. Always verify important
          dates and facts.
        </p>

        <h2>5. Your content</h2>
        <p>
          You retain ownership of the audio and transcripts you submit. You grant us a limited
          license to process them solely to provide the Service (transcription, analysis, storage,
          and display back to you). See our{" "}
          <Link href="/privacy" className="font-medium text-slate-900 underline">
            Privacy Policy
          </Link>{" "}
          for details.
        </p>

        <h2>6. Acceptable use</h2>
        <p>
          Don&rsquo;t misuse the Service: no unlawful content, no attempts to break, overload, or
          reverse-engineer it, and no sharing of one account across many people to evade plan limits.
        </p>

        <h2>7. Disclaimers &amp; liability</h2>
        <p>
          The Service is provided &ldquo;as is&rdquo; without warranties of any kind. To the maximum
          extent permitted by law, we are not liable for indirect or consequential damages, and our
          total liability is limited to the amount you paid us in the prior three months.
        </p>

        <h2>8. Termination</h2>
        <p>
          You may stop using the Service at any time. We may suspend or terminate accounts that
          violate these Terms. You can request deletion of your data as described in the Privacy
          Policy.
        </p>

        <h2>9. Changes</h2>
        <p>
          We may update these Terms; material changes will be posted here with a new effective date.
          Continued use after changes means you accept them.
        </p>

        <h2>10. Contact</h2>
        <p>
          Questions? Reach us at{" "}
          <a href={`mailto:${CONTACT_EMAIL}`} className="font-medium text-slate-900 underline">
            {CONTACT_EMAIL}
          </a>
          .
        </p>

        <p className="mt-8 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800">
          This is a starting template, not legal advice. Have it reviewed by a qualified attorney
          before relying on it — especially the recording-consent, refund, and liability sections.
        </p>
      </div>
    </main>
  );
}
